# -*- coding: utf-8 -*-
"""bubble sort с оптимизацией

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcH3pW1cKHb5QPK67jnzO-uuFpGVL_Sz
"""

import random

def bubble_sort(lst: list[int]) -> list[int]:
    """
    Реализация пузырьковой сортировки с флагом swapped (оптимизация).
    Сортировка происходит 'на месте' (in-place).
    """
    n = len(lst)
    for i in range(n):
        swapped = False  # Флаг для раннего выхода
        for j in range(0, n - i - 1):
            if lst[j] > lst[j + 1]:
                # Обмен соседних элементов
                lst[j], lst[j + 1] = lst[j + 1], lst[j]
                swapped = True

        # Если перестановок не было, массив уже упорядочен
        if not swapped:
            break
    return lst

lst1 = [random.randint(1, 100) for _ in range(10)]
lst2 = [random.randint(1, 100) for _ in range(10)]
print(f"Исходный массив1: {lst1}")
print(f"Исходный массив2: {lst2}")

# Вызов функции и вывод результата
print(f"Отсортированный массив1: {bubble_sort(lst1)}")

print(f"Отсортированный массив2: {bubble_sort(lst2)}")