# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywKSEZQVQY_WUsul2OmLCrKJPCz3Yb-3
"""

import heapq
from collections import Counter

# Класс для узла дерева Хаффмана
class HuffmanNode:
    def __init__(self, char, freq):
        self.char = char      # Символ (None для внутренних узлов)
        self.freq = freq      # Частота появления
        self.left = None      # Левый потомок
        self.right = None     # Правый потомок

    # Переопределение метода сравнения для очереди с приоритетом (min-heap)
    def __lt__(self, other):
        return self.freq < other.freq

def build_huffman_tree(text):
    """Строит дерево Хаффмана на основе частоты символов в тексте"""
    frequency = Counter(text)

    # Создаем очередь с приоритетом (min-heap) из листьев
    priority_queue = [HuffmanNode(char, freq) for char, freq in frequency.items()]
    heapq.heapify(priority_queue)

    # Объединяем узлы, пока не останется один корень
    while len(priority_queue) > 1:
        left_node = heapq.heappop(priority_queue)
        right_node = heapq.heappop(priority_queue)

        # Создаем новый внутренний узел с суммарной частотой
        merged_node = HuffmanNode(None, left_node.freq + right_node.freq)
        merged_node.left = left_node
        merged_node.right = right_node

        heapq.heappush(priority_queue, merged_node)

    return priority_queue[0] if priority_queue else None

def generate_huffman_codes(node, current_code, huffman_codes):
    """Рекурсивно обходит дерево и записывает коды для каждого символа"""
    if node is None:
        return

    # Если это лист, сохраняем накопленный код
    if node.char is not None:
        huffman_codes[node.char] = current_code
        return

    # Рекурсия: влево добавляем '0', вправо '1'
    generate_huffman_codes(node.left, current_code + "0", huffman_codes)
    generate_huffman_codes(node.right, current_code + "1", huffman_codes)

def huffman_encode(text):
    """Основная функция для кодирования строки"""
    if not text:
        return "", None

    root = build_huffman_tree(text)
    huffman_codes = {}
    generate_huffman_codes(root, "", huffman_codes)

    # Собираем финальную битовую строку
    encoded_text = "".join(huffman_codes[char] for char in text)
    return encoded_text, root

def huffman_decode(encoded_text, root):
    """Основная функция для декодирования битовой последовательности"""
    if not encoded_text or root is None:
        return ""

    decoded_text = []
    current_node = root

    for bit in encoded_text:
        # Спускаемся по дереву: 0 - влево, 1 - вправо
        if bit == '0':
            current_node = current_node.left
        else:
            current_node = current_node.right

        # Если достигли листа, добавляем символ в результат и возвращаемся в корень
        if current_node.left is None and current_node.right is None:
            decoded_text.append(current_node.char)
            current_node = root

    return "".join(decoded_text)

# Исходный текст для проверки
test_text = "greedy algorithms solve problems"

# 1. Запускаем кодирование
encoded_res, tree_root = huffman_encode(test_text)

# 2. Запускаем декодирование
decoded_res = huffman_decode(encoded_res, tree_root)

# Вывод результатов для наглядности
print(f"Оригинал: {test_text}")
print(f"Закодировано: {encoded_res}")
print(f"Декодировано: {decoded_res}")
print(f"Результат совпадает: {test_text == decoded_res}")