# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGOHZko2d-S1p6XdNZbh_iUb6pcobtR1
"""

import random

def partition(arr, low, high):
    """
    Процедура разделения Ломуто.
    Выбирает последний элемент как опорный (pivot) и перемещает элементы меньше
    опорного влево, а больше — вправо.
    """
    pivot = arr[high]  # Опорный элемент
    i = low - 1        # Указатель для элементов меньше pivot

    for j in range(low, high):
        # Если текущий элемент меньше или равен опорному
        if arr[j] <= pivot:
            i += 1
            # Обмен элементами для поддержания порядка
            arr[i], arr[j] = arr[j], arr[i]

    # Ставим опорный элемент на его финальное место
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quick_select(arr, k, low=0, high=None):
    """
    Возвращает k-й наименьший элемент в массиве arr (k с нуля).
    """
    if high is None:
        high = len(arr) - 1

    if low == high:
        return arr[low]

    # Рандомизация опорного элемента
    rand_index = random.randint(low, high)
    arr[rand_index], arr[high] = arr[high], arr[rand_index]

    pi = partition(arr, low, high)

    if k == pi:
        return arr[k]
    elif k < pi:
        return quick_select(arr, k, low, pi - 1)
    else:
        return quick_select(arr, k, pi + 1, high)

# Проверка: ищем 3-й по величине элемент (индекс k=2)
B = [8, 4, 7, 3, 1, 9, 6]
k_val = 2
result = quick_select(B, k_val)
print(f"{k_val + 1}-й наименьший элемент: {result}")