# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gB95XuYQB9gGZ8AYIeMPJEQpToxgiFMV
"""

import random

def partition(arr, low, high):
    """
    Процедура разделения Ломуто.
    Выбирает последний элемент как опорный (pivot) и перемещает элементы меньше
    опорного влево, а больше — вправо.
    """
    pivot = arr[high]  # Опорный элемент
    i = low - 1        # Указатель для элементов меньше pivot

    for j in range(low, high):
        # Если текущий элемент меньше или равен опорному
        if arr[j] <= pivot:
            i += 1
            # Обмен элементами для поддержания порядка
            arr[i], arr[j] = arr[j], arr[i]

    # Ставим опорный элемент на его финальное место
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quick_sort(arr, low, high):
    """
    Основная функция QuickSort с рандомизацией.
    Сортирует массив 'на месте' (in-place).
    """
    if low < high:
        # Рандомизация: выбираем случайный индекс в текущем диапазоне
        rand_index = random.randint(low, high)
        # Меняем случайный элемент с последним, чтобы использовать его как pivot в Ломуто
        arr[rand_index], arr[high] = arr[high], arr[rand_index]

        # Разделение массива и получение индекса опорного элемента
        pi = partition(arr, low, high)

        # Рекурсивно сортируем левую и правую части (Разделяй и властвуй)
        quick_sort(arr, low, pi - 1)
        quick_sort(arr, pi + 1, high)

# Проверка работы
test_arr = [8, 4, 7, 3, 1, 9, 6]
print(f"До сортировки: {test_arr}")
quick_sort(test_arr, 0, len(test_arr) - 1)
print(f"После QuickSort: {test_arr}")