# -*- coding: utf-8 -*-
"""selection sort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZ8CDq1j_Q-LOKcNcamZeu-g069N7PUi
"""

import random

def selection_sort(lst: list[int]) -> list[int]:
    """
    Алгоритм сортировки выбором.
    Находит индекс минимального элемента и ставит его в начало.
    """
    n = len(lst)
    for i in range(n):
        # Поиск индекса минимального элемента в оставшейся части
        min_idx = i
        for j in range(i + 1, n):
            if lst[j] < lst[min_idx]:
                min_idx = j

        # Обмен текущего элемента с найденным минимальным
        if min_idx != i:
            lst[i], lst[min_idx] = lst[min_idx], lst[i]

    return lst

# Тестовый массив из 10 случайных чисел от 1 до 100
lst1 = [random.randint(1, 100) for _ in range(10)]
lst2 = [random.randint(1, 100) for _ in range(10)]
print(f"Исходный массив для выбора1: {lst1}")
print(f"Исходный массив для выбора2: {lst2}")

print(f"Результат сортировки выбором1: {selection_sort(lst1)}")

print(f"Результат сортировки выбором2: {selection_sort(lst2)}")