# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2gPeZXAfNYTPR0v9nFf2Xeixl_LJCsO
"""

import time
import random
import copy
import matplotlib.pyplot as plt
import pandas as pd

def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        L, R = arr[:mid], arr[mid:]
        merge_sort(L)
        merge_sort(R)

        i = j = k = 0
        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                arr[k] = L[i]; i += 1
            else:
                arr[k] = R[j]; j += 1
            k += 1
        while i < len(L):
            arr[k] = L[i]; i += 1; k += 1
        while j < len(R):
            arr[k] = R[j]; j += 1; k += 1
    return arr

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

def get_random(n):
    return [random.randint(0, 100000) for _ in range(n)]

def get_sorted(n):
    return sorted(get_random(n))

def get_reverse(n):
    return sorted(get_random(n), reverse=True)

def get_nearly_sorted(n):
    arr = get_sorted(n)
    swaps = int(n * 0.05) // 2
    for _ in range(swaps):
        i, j = random.randint(0, n-1), random.randint(0, n-1)
        arr[i], arr[j] = arr[j], arr[i]
    return arr

# Словарь генераторов для удобного вызова в цикле
data_generators = {
    "Случайные": get_random,
    "Отсортированные": get_sorted,
    "Почти отсортированные": get_nearly_sorted,
    "Обратные": get_reverse
}

sizes = [1000, 5000, 10000, 50000]
runs = 5

# Здесь будут храниться все собранные данные
all_results = {}

for data_name, generator in data_generators.items():
    print(f"Собираем данные: {data_name}...")
    all_results[data_name] = {'sizes': sizes, 'merge': [], 'insertion': []}

    for n in sizes:
        total_merge, total_insertion = 0, 0

        for _ in range(runs):
            original_arr = generator(n)

            # Тест Merge Sort
            arr_copy1 = copy.deepcopy(original_arr)
            start = time.perf_counter()
            merge_sort(arr_copy1)
            total_merge += (time.perf_counter() - start)

            # Тест Insertion Sort
            arr_copy2 = copy.deepcopy(original_arr)
            start = time.perf_counter()
            insertion_sort(arr_copy2)
            total_insertion += (time.perf_counter() - start)

        # Усредняем и сохраняем
        all_results[data_name]['merge'].append(total_merge / runs)
        all_results[data_name]['insertion'].append(total_insertion / runs)

print("Тестирование завершено!")

import math

# Определяем количество графиков и размер сетки
num_plots = len(all_results)
num_cols = 2
num_rows = math.ceil(num_plots / num_cols)

plt.figure(figsize=(num_cols * 7, num_rows * 5)) # Общий размер для всех подграфиков

for i, (data_name, data) in enumerate(all_results.items()):
    plt.subplot(num_rows, num_cols, i + 1) # Создаем подграфик в сетке
    plt.plot(data['sizes'], data['merge'], marker='o', label='Merge Sort O(n log n)')
    plt.plot(data['sizes'], data['insertion'], marker='o', label='Insertion Sort O(n²)')

    plt.xlabel("Размер входных данных (n)")
    plt.ylabel("Среднее время выполнения (секунды)")
    plt.title(f"Сравнение алгоритмов: {data_name} данные")

    plt.legend()
    plt.grid(True)

plt.tight_layout() # Автоматически регулирует параметры подызображения для плотного заполнения фигуры.
plt.show()

# Формируем данные для таблицы
table_data = []

for data_name, data in all_results.items():
    for i, n in enumerate(data['sizes']):
        table_data.append({
            "Тип данных": data_name,
            "Размер массива (n)": n,
            "Merge Sort (сек)": round(data['merge'][i], 6),
            "Insertion Sort (сек)": round(data['insertion'][i], 6)
        })

# Создаем DataFrame и выводим
df = pd.DataFrame(table_data)
display(df)